package ai

// Copilot completion increment 3 — RAG over case history (§6.12 #180, GATE_COPILOT_COMPLETION_I3_RAG.md). The
// copilot's institutional memory: past-incident chunks are embedded into a PER-TENANT vector store so a similar prior
// case can be recalled to ground an answer. Two non-negotiables, both enforced HERE + by the schema (mig 0143):
//   1. PER-TENANT ISOLATION (the crux): every index/retrieve/purge runs WithTenant(p.TenantID); the table is
//      FORCE-RLS'd, so the similarity query is RLS-confined — a tenant can ONLY ever retrieve its own embeddings. A
//      two-tenant test is the load-bearing proof (drop the tenant scope → cross-tenant retrieval → RED).
//   2. FIELD-VISIBILITY (2b): each chunk carries a min_role floor; RetrieveSimilar returns only chunks the acting
//      analyst may see (auth.RoleRank) — a junior's copilot can't recall a senior-only chunk, same seam as RunHunt.
// Embeddings are generated by a LOCAL deterministic embedder (feature hashing) — NOTHING leaves the perimeter, so no
// new egress door opens (check-ai-egress-redaction stays green). A future cloud/self-hosted embedding provider is a
// documented follow-on that re-enters the gate (its own egress + redaction review). RAG is read-only: this file
// references no soar/mutation symbol (check-ai-no-direct-execution stays green). Retention: mig 0143's FK is
// ON DELETE CASCADE, so a deleted incident's embeddings are purged automatically; PurgeCaseEmbeddings handles age-out.

import (
	"context"
	"fmt"
	"hash/fnv"
	"math"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/ArowuTest/nirvet/internal/platform/auth"
	"github.com/ArowuTest/nirvet/internal/platform/httpx"
)

const (
	ragEmbedDim    = 256 // matches vector(256) in mig 0143; the local embedder's output dimension
	ragMaxChunkLen = 4000
	ragMaxK        = 20 // top-K ceiling — retrieval is bounded (gate §9)
	ragOverfetch   = 5  // over-fetch factor before field-visibility filtering, so masked rows don't starve the top-K
	ragDefaultRole = "analyst_t1"
	ragRecallK     = 5 // default top-K past-case chunks pulled into a recall-grounded copilot answer
)

// RetrievedChunk is one recalled past-case chunk with its citation id (RAG-n at the call site) and its source incident.
type RetrievedChunk struct {
	ID          uuid.UUID `json:"id"`
	IncidentRef uuid.UUID `json:"incident_ref"`
	Chunk       string    `json:"chunk"`
}

// IndexCase embeds a chunk of an incident's history and stores it in the caller's tenant (WithTenant → RLS binds
// tenant_id). minRole is the field-visibility floor (default analyst_t1 = visible to everyone). The chunk is customer
// telemetry; on retrieval it rides completeExternal redacted. Bounded length. Analyst/worker-initiated, not an
// autonomous indexer (gate 2f).
func (s *Service) IndexCase(ctx context.Context, p auth.Principal, incidentRef uuid.UUID, chunk, minRole string) error {
	chunk = strings.TrimSpace(chunk)
	if chunk == "" {
		return httpx.ErrBadRequest("chunk is required")
	}
	if incidentRef == uuid.Nil {
		return httpx.ErrBadRequest("incident_ref is required")
	}
	if len(chunk) > ragMaxChunkLen {
		chunk = truncateUTF8(chunk, ragMaxChunkLen)
	}
	minRole = normalizeMinRole(minRole)
	vec := vecLiteral(localEmbed(chunk))
	return s.db.WithTenant(ctx, p.TenantID, func(ctx context.Context, tx pgx.Tx) error {
		// incident_ref FK (ON DELETE CASCADE) + RLS ensure the chunk binds to a real incident in THIS tenant; a
		// foreign/nonexistent incident id fails the FK.
		_, err := tx.Exec(ctx,
			`INSERT INTO ai_case_embeddings (incident_ref, chunk, min_role, embedding)
			 VALUES ($1, $2, $3, $4::vector)`, incidentRef, chunk, minRole, vec)
		if err != nil {
			return httpx.ErrBadRequest("could not index the case chunk (incident must exist in your tenant)")
		}
		return nil
	})
}

// RetrieveSimilar returns up to k past-case chunks most similar to the query, in the caller's tenant only (WithTenant
// → RLS), filtered to what the acting analyst's role may see (field-visibility, gate 2b). The returned chunks are the
// caller's to feed to the LLM as the REDACTED, UNTRUSTED evidence bag (never the trusted task). It over-fetches then
// masks so field-visibility filtering doesn't starve the top-K.
func (s *Service) RetrieveSimilar(ctx context.Context, p auth.Principal, query string, k int) ([]RetrievedChunk, error) {
	query = strings.TrimSpace(query)
	if query == "" {
		return nil, nil
	}
	if k <= 0 {
		k = 5
	}
	if k > ragMaxK {
		k = ragMaxK
	}
	vec := vecLiteral(localEmbed(query))
	fetch := k * ragOverfetch
	if fetch > ragMaxK*ragOverfetch {
		fetch = ragMaxK * ragOverfetch
	}

	var out []RetrievedChunk
	err := s.db.WithTenant(ctx, p.TenantID, func(ctx context.Context, tx pgx.Tx) error {
		// RLS confines this to the caller's tenant — THE crux. Cosine distance (<=>) ascending = most similar first.
		rows, err := tx.Query(ctx,
			`SELECT id, incident_ref, chunk, min_role
			   FROM ai_case_embeddings
			  ORDER BY embedding <=> $1::vector
			  LIMIT $2`, vec, fetch)
		if err != nil {
			return err
		}
		defer rows.Close()
		for rows.Next() {
			var c RetrievedChunk
			var minRole string
			if err := rows.Scan(&c.ID, &c.IncidentRef, &c.Chunk, &minRole); err != nil {
				return err
			}
			// Field-visibility (2b): the acting analyst must MEET the chunk's min_role, else it is not recalled — a
			// junior's copilot cannot surface a senior-only chunk. Applied at retrieval, before returning to the caller.
			if auth.RoleRank(p.Role) < auth.RoleRank(auth.Role(minRole)) {
				continue
			}
			out = append(out, c)
			if len(out) >= k {
				break
			}
		}
		return rows.Err()
	})
	if err != nil {
		return nil, httpx.ErrInternal("could not retrieve case history")
	}
	return out, nil
}

// PurgeCaseEmbeddings deletes an incident's embeddings in the caller's tenant (retention age-out / re-index). Incident
// HARD-deletion is already handled by the FK's ON DELETE CASCADE (mig 0143); this covers age-out where the incident
// row remains but its recall memory must be dropped. WithTenant → RLS confines the purge to the tenant.
func (s *Service) PurgeCaseEmbeddings(ctx context.Context, p auth.Principal, incidentRef uuid.UUID) (int, error) {
	var n int64
	err := s.db.WithTenant(ctx, p.TenantID, func(ctx context.Context, tx pgx.Tx) error {
		ct, e := tx.Exec(ctx, `DELETE FROM ai_case_embeddings WHERE incident_ref = $1`, incidentRef)
		if e != nil {
			return e
		}
		n = ct.RowsAffected()
		return nil
	})
	if err != nil {
		return 0, httpx.ErrInternal("could not purge case embeddings")
	}
	return int(n), nil
}

// recallFacts retrieves the top past-case chunks most similar to the analyst's query and maps them to CitedFacts
// (RAG-n ids) so they MERGE into the copilot's existing evidence bag exactly like assembled incident facts: id-prefixed,
// redacted at completeExternal, citable, invented-id-stripped. The chunk is UNTRUSTED customer telemetry — it enters as
// `evidence`, NEVER the trusted `task`, so a prompt-injection string ("ignore previous instructions") inside a recalled
// chunk is inert data (gate non-negotiable #2 / the copilot-P0 untrusted-bag pattern). Tenant isolation + field-visibility
// are already enforced inside RetrieveSimilar (WithTenant + RoleRank). Fail-open to no recall on error — the copilot then
// answers on the incident context or says "insufficient evidence" rather than fabricating.
func (s *Service) recallFacts(ctx context.Context, p auth.Principal, query string) []CitedFact {
	chunks, err := s.RetrieveSimilar(ctx, p, query, ragRecallK)
	if err != nil || len(chunks) == 0 {
		return nil
	}
	out := make([]CitedFact, 0, len(chunks))
	for i, c := range chunks {
		f := c.Chunk
		if len(f) > maxCitedFactLen {
			f = truncateUTF8(f, maxCitedFactLen) + "…"
		}
		out = append(out, CitedFact{ID: fmt.Sprintf("RAG-%d", i+1), Fact: f})
	}
	return out
}

// normalizeMinRole clamps an unknown/blank min_role to the light default (analyst_t1 = visible to everyone). An
// unknown role (RoleRank -1) would make a chunk visible to all, which is wrong for a floor — so default to the known
// light floor rather than trust an arbitrary string.
func normalizeMinRole(r string) string {
	r = strings.ToLower(strings.TrimSpace(r))
	if r == "" || auth.RoleRank(auth.Role(r)) < 0 {
		return ragDefaultRole
	}
	return r
}

// localEmbed is a deterministic, in-process embedding (feature hashing / the "hashing trick"): each token is hashed to
// a dimension with a sign, accumulated, then L2-normalized. It shares no state and makes NO network call — nothing
// leaves the perimeter (the sovereign default; gate 2c). Similar text → similar vectors (shared tokens land in the
// same dims), so cosine similarity is meaningful for recall. It is NOT a semantic model — quality is limited vs. a
// real embedding model; a cloud/self-hosted embedding provider is the documented upgrade (each re-enters the gate).
func localEmbed(text string) []float32 {
	vec := make([]float32, ragEmbedDim)
	for _, tok := range tokenizeForEmbed(text) {
		h := fnv.New32a()
		_, _ = h.Write([]byte(tok))
		sum := h.Sum32()
		dim := sum % ragEmbedDim
		if (sum>>9)&1 == 1 {
			vec[dim] -= 1
		} else {
			vec[dim] += 1
		}
	}
	// L2-normalize so cosine distance is well-behaved; a zero vector stays zero (an empty/garbage chunk).
	var norm float64
	for _, v := range vec {
		norm += float64(v) * float64(v)
	}
	if norm > 0 {
		inv := float32(1 / math.Sqrt(norm))
		for i := range vec {
			vec[i] *= inv
		}
	}
	return vec
}

// tokenizeForEmbed lowercases and splits on non-alphanumeric runs — a simple bag-of-tokens for the hashing embedder.
func tokenizeForEmbed(text string) []string {
	text = strings.ToLower(text)
	return strings.FieldsFunc(text, func(r rune) bool {
		return !((r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'))
	})
}

// vecLiteral renders a []float32 as a pgvector text literal `[v0,v1,...]` for the `$n::vector` cast (pgx has no native
// vector codec). The values are ours (an embedding), never customer text, so this is inert to inject.
func vecLiteral(v []float32) string {
	var b strings.Builder
	b.WriteByte('[')
	for i, x := range v {
		if i > 0 {
			b.WriteByte(',')
		}
		fmt.Fprintf(&b, "%g", x)
	}
	b.WriteByte(']')
	return b.String()
}
