{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nirvet.fullname" . }}-worker
  labels: {{- include "nirvet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels: {{- include "nirvet.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels: {{- include "nirvet.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "nirvet.fullname" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      securityContext: {{- include "nirvet.podSecurityContext" . | nindent 8 }}
      containers:
        - name: worker
          image: {{ include "nirvet.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/worker"]
          securityContext: {{- include "nirvet.containerSecurityContext" . | nindent 12 }}
          envFrom: {{- include "nirvet.envFrom" . | nindent 12 }}
          resources: {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
{{- end }}
